#!/usr/bin/env php
<?php

if (file_exists(__DIR__.'/vendor/autoload.php')) {
    require __DIR__.'/vendor/autoload.php';
} else {
    require __DIR__.'/../../autoload.php';
}

$app = new Symfony\Component\Console\Application('Laravel Envoy', '1.3.2');

$app->add(new Sanuj\Diplomat\Console\RunCommand);
$app->add(new Sanuj\Diplomat\Console\SshCommand);
$app->add(new Sanuj\Diplomat\Console\InitCommand);
$app->add(new Sanuj\Diplomat\Console\TasksCommand);

$app->run();
